@echo off
echo Starting Bike Service Application...

echo Starting Backend...
start cmd /k "cd backend && mvn spring-boot:run"

echo Starting Frontend...
start cmd /k "cd frontend && npm start"

echo Applications are starting...
echo Backend will be available at http://localhost:8080
echo Frontend will be available at http://localhost:3000 